name: Build & upload Docker images tar

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-folder: [opendart-postprocess]   # 추가 이미지 폴더 추가 가능
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ matrix.image-folder }}
          TAG_NAME=${GITHUB_REF_NAME}
          docker build -t $IMAGE_NAME:$TAG_NAME ./${{ matrix.image-folder }}

      - name: Save Docker image to tar.gz
        run: |
          IMAGE_NAME=${{ matrix.image-folder }}
          TAG_NAME=${GITHUB_REF_NAME}
          mkdir -p artifacts
          docker save $IMAGE_NAME:$TAG_NAME -o artifacts/$IMAGE_NAME-$TAG_NAME.tar
          gzip -f artifacts/$IMAGE_NAME-$TAG_NAME.tar

      - name: Upload tar.gz to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/${{ matrix.image-folder }}-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
